### ISSUE TITLE
Unable to connect with docker on MacOS

### ISSUE THREAD

**Issue by RodolfoSilva** [nakagami/firebirdex#21]
The server works with the dBeaver JDBCDriver
But, I'm getting a `:killed` signal following the example from the readme:

This is my docker-compose file

```yaml
version: "3.8"
services:
  firebird:
    image: jacobalberty/firebird:v3.0
    restart: unless-stopped
    environment:
      ISC_PASSWORD: masterkey
    ports:
      - 3050:3050
    volumes:
      - ./data:/firebird/data
```

```elixir
opts = [ 
  hostname: "localhost:3050",
  username: "SYSDBA",
  password: "masterkey",
  database: "/firebird/data/MY.fdb"
]

{:ok, pid} = Firebirdex.start_link(opts)
```

I'm geting this error:

<img width="509" alt="image" src="https://github.com/nakagami/firebirdex/assets/1703020/5876cbe6-76e1-4597-b293-2623c0a5aa03">
